# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'windows.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(90, 40, 141, 32))
        self.comboBox.setObjectName("comboBox")
        self.choice_Leagunge = QtWidgets.QComboBox(self.centralwidget)
        self.choice_Leagunge.setGeometry(QtCore.QRect(450, 510, 141, 32))
        self.choice_Leagunge.setObjectName("choice_Leagunge")
        self.Submit = QtWidgets.QPushButton(self.centralwidget)
        self.Submit.setGeometry(QtCore.QRect(600, 490, 151, 51))
        self.Submit.setObjectName("Submit")
        self.question = QtWidgets.QTextBrowser(self.centralwidget)
        self.question.setGeometry(QtCore.QRect(90, 80, 651, 231))
        self.question.setObjectName("question")
        self.choice_question = QtWidgets.QTextBrowser(self.centralwidget)
        self.choice_question.setGeometry(QtCore.QRect(90, 20, 71, 21))
        self.choice_question.setObjectName("choice_question")
        self.Lg_txt = QtWidgets.QTextBrowser(self.centralwidget)
        self.Lg_txt.setGeometry(QtCore.QRect(460, 490, 71, 21))
        self.Lg_txt.setObjectName("Lg_txt")
        self.choice_file = QtWidgets.QPushButton(self.centralwidget)
        self.choice_file.setGeometry(QtCore.QRect(280, 500, 121, 31))
        self.choice_file.setObjectName("choice_file")
        self.example_in = QtWidgets.QTextBrowser(self.centralwidget)
        self.example_in.setGeometry(QtCore.QRect(90, 320, 321, 121))
        self.example_in.setObjectName("example_in")
        self.example_out = QtWidgets.QTextBrowser(self.centralwidget)
        self.example_out.setGeometry(QtCore.QRect(420, 320, 321, 121))
        self.example_out.setObjectName("example_out")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 24))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Submit.setText(_translate("MainWindow", "送出"))
        self.choice_question.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'.AppleSystemUIFont\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">選擇題目</p></body></html>"))
        self.Lg_txt.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'.AppleSystemUIFont\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">選擇語言</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.choice_file.setText(_translate("MainWindow", "選擇檔案"))
    
    def setup_control(ui):
        ui.ui.file_button.clicked.connect(ui.choice_file)
        ui.ui.folder_button.clicked.connect(ui.open_folder)
        
    def open_file(self):
        filename, filetype = QFileDialog.get.getOpenFileName(self,
                  "Open file",
                  "./")
        print(filename, filetype)
        self.ui.show_file_path.setText(filename)


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    ui.setup_control()
    MainWindow.show()
    sys.exit(app.exec_())
